using Kontent.Ai.Management.Configuration;
using Kontent.Ai.Management.Models.Types.Elements;
using Kontent.Ai.Management.Models.Types;
using Kontent.Ai.Management;
using MortgageManager.Entities.Models;
using Kontent.Ai.Management.Models.Items;
using Kontent.Ai.Management.Models.Shared;
using Kontent.Ai.Management.Models.LanguageVariants.Elements;
using Kontent.Ai.Management.Models.LanguageVariants;
using Kontent.Ai.Management.Models.Workflow;
using Kontent.Ai.Management.Modules.ModelBuilders;
using Microsoft.VisualBasic;

namespace MortgageManager.CMS
{
    public class MortgageCreator
    {

        private ManagementClient _client = new ManagementClient(new ManagementOptions
        {
            ApiKey = "<YOUR_API_KEY>",
        });

        public async Task<bool> UploadMortgageProduct(Product product)
        {
            Guid itemId;
            itemId = await CreateProduct(product);

            var identifier = new LanguageVariantIdentifier(Reference.ById(itemId), Reference.ByCodename("en-GB"));

            await UpdateProductDetails(identifier);

            return true;
        }

        private async Task UpdateProductDetails(LanguageVariantIdentifier identifier)
        {
            var response = await _client.UpsertLanguageVariantAsync(identifier,
                new LanguageVariantUpsertModel
                {
                    Elements = ElementBuilder.GetElementsAsDynamic(new BaseElement[]
                    {
                        new UrlSlugElement
                        {
                            Element = Reference.ByCodename("url_pattern"),
                            Mode = "autogenerated"
                        }
                    },
                    new WorkflowStepIdentifier(Reference.ByCodename("default"), Reference.ByCodename("review"))
                    )
                });
        }

        private async Task<Guid> CreateProduct(Product product)
        {
            var response = await _client.CreateContentItemAsync(new ContentItemCreateModel
            {
                Name = product.Name,
                Codename = product.Name?.Replace(" ", "_").ToLower(),
                Type = Reference.ByCodename("product_mortgage"),
                Collection = Reference.ByCodename("default"),
            });

            return response.Id;
        }
    }
}
